
# enable app support
APP=1
APP_STACKSIZE=300

VPATH += src/
PROJ_OBJ += app_dronet.o
PROJ_OBJ += uart_dma_pulp.o
INCLUDES += -Iinc

CRAZYFLIE_BASE=../crazyflie-firmware
include $(CRAZYFLIE_BASE)/Makefile